openapi: "3.0.0"
info:
  title: referentiel-personnes
  description: API du referentiel des personnes
  version: 1.0.0
  licence:
    name: Apache Licence 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: https://meltingpoc.k8.wildwidewest.xyz/api-personnes-mock
paths:
  /personnes:
    get:
      operationId: getPersonnes
      summary: Recuperer personnes
      description: |-
        Retourne toutes les personnes du référentiel
      responses:
        '200':
          description: |-
            Une liste de personnes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/schemas/Personne'
    post:
      operationId: createPersonne
      summary: Création d'une personne
      description: |-
        Permet la création d'une personne
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/schemas/Personne'
      responses:
        '201':
          description: |-
            La personne a été créée
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Personne'
        '400':
          description: |-
            Erreur lors de la création de la personne
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Erreur'
  /personnes/{id}:
    get:
      operationId: getPersonne
      summary: Recuperer personne
      description: |-
        Recherche une personne via son identifiant technique.
      parameters:
      - name: id
        in: path
        description: |-
          Identifiant de la personne
        required: true
        schema:
          type: string
      responses:
        '200':
          description: |-
            La personne trouvé
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Personne'
    delete:
      operationId: deletePersonne
      summary: Suppression d'une personne
      description: |-
        Suppression d'une personne via son identifiant technique.
      parameters:
      - name: id
        in: path
        description: |-
          Identifiant de la personne
        required: true
        schema:
          type: string
      responses:
        '200':
          description: |-
            La personne a été supprimée
        '400':
          description: |-
            Erreur lors de la création de la personne
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Erreur'
    put:
      operationId: updatePersonne
      summary: Modification d'une personne
      description: |-
        Permet la mise à jour d'une personne
      parameters:
        - name: id
          in: path
          description: |-
            Identifiant de la personne
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/definitions/schemas/Personne'
      responses:
        '200':
          description: |-
            La personne a été mise à jour
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Personne'
        '400':
          description: |-
            Erreur lors de la modification de la personne
          content:
            application/json:
              schema:
                $ref: '#/definitions/schemas/Erreur'
definitions:
  schemas:
    Personne:
      $ref: ./schemas/personne.yaml
    Erreur:
      $ref: ./schemas/erreur.yaml