apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meltingpoc-api-personnes-swagger
spec:
  replicas: 1
  template:
    metadata:
     labels:
        app: meltingpoc-api-personnes-swagger
    spec:
      containers:
      - name: meltingpoc-mock
        image: registry.k8.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc-api-personnes-swagger
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  name: meltingpoc-api-personnes-swagger
spec:
  selector:
    app: meltingpoc-api-personnes-swagger
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080