apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: meltingpoc-api-personnes-mock
spec:
  replicas: 1
  template:
    metadata:
     labels:
        app: meltingpoc-api-personnes-mock
    spec:
      containers:
      - name: meltingpoc-mock
        image: registry.wildwidewest.xyz/repository/docker-repository/pocs/meltingpoc-api-personnes-mock
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  name: meltingpoc-api-personnes-mock
spec:
  selector:
    app: meltingpoc-api-personnes-mock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000